### PR TITLE
Adding turbolinks

### PR DESCRIPTION
**Pull request by naps62**

### CODE REVIEW

**Comment by gabrielpoca** [comment]
Doesn't it affect the navbar in any way?

**Comment by naps62** [comment]
didn't look like it. `jquery.turbolinks` should handle that, but i'll test a bit more tomorrow

**Comment by zamith** [comment]
Have you thought of adding turbolinks page cache? Does it make sense?

**Comment by naps62** [comment]
@zamith Don't know, never worked with that. Can that be addressed later on (by you possibly?)

**Comment by zamith** [comment]
@naps62 In theory you just have to change a config from false to true, but it might have some issues with other JS. And maybe it's not even worth it, because the bounce rate is so high that users won't really take any advantage of it, just wanted to know if you had thought of it.

**Pull request merged**
