### PR TITLE
Removes Decorators

### PR DESCRIPTION
**Pull request by naps62**
Most of the methods in the two existing decorators were no longer being used
since the redesign

As for the remaining ones, I feel there's not that many as to justify the
inclusion of a large gem such as draper. And at the same time, I feel they're
fine as view helpers

Changes:
- Removes draper decorators
- Removes several unused methods, and their respective specs
- Moves the few used decorator methods into helper methods (and a couple of
  them to plain model methods)

### CODE REVIEW

**Comment by zamith** [comment]
What about moving all the methods to models, instead of having helpers?

**Comment by naps62** [comment]
The ones I moved to helpers are entirely related to the views, so that wouldn't make much sense I think

Plus, they usually depend on other helpers (such as `image_path`, or `raw`), which usually isn't something you want to deal with in a model

**Comment by zamith** [comment]
Sure, the model is not the ideal place, a decorator is. But since we're getting rid of those I think a model beats a helper, which is basically a global method. That's my issue with helpers.

**Comment by naps62** [comment]
I don't like calling them global methods, because they're only visible to the views & controllers. I see the point in saying that, but still, they're in a more controlled scope.
Global variables are bad mostly because you can reference them anywhere. This is not the case here. Your models or PORO's are still safe

I understand the issues people have against helpers, but I'm OK with them if they're being used to work on top of the existing view helpers, or to do similar behaviour (i.e. generate html for the views. Or URLs in the case of the route helpers)

Having these in the models would force me to call `ActionController::Base.helpers.image_path` instead of just `image_path`. Which not only looks bad, but it's actually a disadvantage against my previous point about helpers. The one good thing about helpers is that they're not accessible by default in models/etc, which is what I'd have to do here

Anyway if you still feel strongly about that I can change it. There's no much to gain in extending this discussion :smiley:

**Pull request closed without merging**
